name: Next.js Build

on:
  push:
    branches:
      - main
      - eddy
      - johan
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: ""

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.8.1

    - name: Install dependencies
      run: npm i

    - name: Build
      run: npm run build