name: Next.js Build

on:
  push:
    branches:
      - main
      - eddy
      - johan
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: "file:./db.sqlite"

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm i

    - name: Build
      run: npm run build